{
 "title": "POWDER 5G",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "filter" },
   {
    "name": "query0",
    "label": "Job",
    "query": {}
   },
   {
    "name": "query1",
    "label": "Bus",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "log events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({job=~\"srs-gnb|open5gs|quectel-cm|ue-metrics\"}[$__interval])"
    }
   ]
  },
  {
   "title": "UE",
   "type": "logs",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=~\"quectel-cm|ue-metrics\"} |= `$filter` | host = `$query1`",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 28, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"gps\", host=\"$query1\"} | json | class = `TPV`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "UE metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=~\"ue-metrics\"} | host = `$query1` |= `NR5G-SA` | pattern `<_> \"<cmd>\",\"<status>\",\"<rat>\",\"<frame_cfg>\", <mcc>,<mnc>,<cell_id>,<pci>,<tac>,<arfcn>,<band>,<bw>,<rsrp>,<rsrq>,<sinr>,<tx_power>,<srxlev>`",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Core Network",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{job=~\"open5gs\"} |= `$filter`",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "gNodeB",
   "type": "logs",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{job=~\"srs-gnb|srs-gnb-log|srs-gnb-trace\"} |= `$filter`",
     "maxLines": 1000
    }
   ]
  }
 ]
}